<a href="https://colab.research.google.com/github/siddhidamkondwar/Practical_Machine_Learning/blob/main/ML_22_6_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import scipy
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import pylab
import statsmodels
import statsmodels.api as sm
import statsmodels.stats.multicomp
import statsmodels.stats
import statsmodels.api as sm
import statsmodels.stats.multicomp
import sklearn

from numpy import linalg
from scipy import stats
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import norm, t
from scipy.stats import expon
from collections import Counter
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.formula.api import ols
from statsmodels.stats.proportion import proportions_ztest
from scipy.stats import chisquare
from scipy.stats import chi2_contingency
from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson
from statsmodels.stats.rates import test_poisson_2indep
from statsmodels.formula.api import ols
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name='PCA_LDA_Data')

In [ ]:
preds = df.drop('y',axis=1)

In [ ]:
resp = df.y

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(preds,resp, test_size=0.2,random_state=42)

In [ ]:
x_train

        X1    X2    X3   X4   X5   X6
968   38.5  37.0  33.1  1.7  2.4  2.0
240   24.3  24.2  19.9  1.5  1.7  1.8
819   42.0  36.3  32.2  0.5  1.0  0.4
692   22.8  21.1  20.3  1.5  2.0  1.4
420   22.6  20.8  24.0  1.6  1.8  1.1
...    ...   ...   ...  ...  ...  ...
1130  25.5  21.0  19.4  1.2  2.5  1.4
1294  34.8  33.3  29.9  1.1  0.8  1.2
860   29.9  28.1  22.8  1.7  1.7  2.1
1459  21.0  20.1  17.6  1.7  3.2  0.2
1126  41.6  35.8  32.5  0.5  1.5  1.0

[1600 rows x 6 columns]

In [ ]:
x_train = sm.add_constant(x_train,prepend=False)

In [ ]:
mod1=sm.Logit(y_train,x_train).fit()

Optimization terminated successfully.
         Current function value: 0.396269
         Iterations 7

In [ ]:
print(mod1.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                 1600
Model:                          Logit   Df Residuals:                     1593
Method:                           MLE   Df Model:                            6
Date:                Mon, 22 Jun 2026   Pseudo R-squ.:                  0.4277
Time:                        04:19:48   Log-Likelihood:                -634.03
converged:                       True   LL-Null:                       -1107.8
Covariance Type:            nonrobust   LLR p-value:                1.912e-201
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
X1             0.0130      0.038      0.339      0.734      -0.062       0.088
X2             0.0275      0.042      0.658      0.511      -0.054       0.109
X3            -0.0519      0.044     -1.186      0.235      -0.138       0.034
X4             1.1250      0.071     15.903      0.000       0.986       1.264
X5             1.1095      0.070     15.800      0.000       0.972       1.247
X6             1.0292      0.070     14.688      0.000       0.892       1.167
const         -6.2553      0.361    -17.305      0.000      -6.964      -5.547
==============================================================================

In [ ]:
# --- Scaling ---
sc1 = StandardScaler()
x_train_sc = sc1.fit_transform(x_train)
x_test_sc = sc1.transform(x_test)

In [ ]:
# Convert back to DataFrames correctly
x_train_sc = pd.DataFrame(x_train_sc, columns=x_train.columns, index=x_train.index)
x_test_sc = pd.DataFrame(x_test_sc, columns=x_test.columns, index=x_test.index)

In [ ]:

# --- PCA ---
from sklearn.decomposition import PCA
pca = PCA(n_components=2)

In [ ]:

x_train_pca = pca.fit_transform(x_train_sc)
x_test_pca = pca.transform(x_test_sc)

In [ ]:
# Convert PCA arrays to DataFrames
x_train_pca = pd.DataFrame(x_train_pca, columns=['PC1', 'PC2'], index=x_train.index)
x_test_pca = pd.DataFrame(x_test_pca, columns=['PC1', 'PC2'], index=x_test.index)

In [ ]:

# --- Add Constant for Statsmodels Logit ---
x_train_pca = sm.add_constant(x_train_pca, prepend=False)
x_test_pca = sm.add_constant(x_test_pca, prepend=False)

In [ ]:
x_train_pca

           PC1       PC2  const
968   1.094665 -0.199867    1.0
240  -0.984222 -0.278963    1.0
819   1.213284 -1.139653    1.0
692  -1.177128 -0.543566    1.0
420  -0.983309 -0.562719    1.0
...        ...       ...    ...
1130 -1.100575 -0.831382    1.0
1294  0.561720 -0.448143    1.0
860  -0.366067 -0.021355    1.0
1459 -1.429488 -1.300218    1.0
1126  1.175297 -1.013049    1.0

[1600 rows x 3 columns]

In [ ]:
mod2 = sm.Logit(y_train,x_train_pca).fit()

Optimization terminated successfully.
         Current function value: 0.630170
         Iterations 5

In [ ]:
x_test_pca = sm.add_constant(x_test_pca, prepend=False)

In [ ]:
y_pred =mod2.predict(x_test_pca)

In [ ]:
y_pred = (y_pred>0.5).astype(int)

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[150  52]
 [ 91 107]]

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name = 'PCA_LDA_Data')

preds = df.drop('y', axis=1)
resp = df.y

x_train, x_test, y_train, y_test = train_test_split(preds,resp,test_size=0.2, random_state=20)

sc1 = StandardScaler()

x_train_sc = sc1.fit_transform(x_train)
x_test_sc = sc1.transform(x_test)

x_train_sc = pd.DataFrame(x_train_sc, columns=x_train.columns, index=x_train.index)
x_test_sc = pd.DataFrame(x_test_sc, columns=x_test.columns, index=x_test.index)
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()


x_train_lda = lda.fit_transform(x_train_sc,y_train)
x_test_lda = lda.transform(x_test_sc)

x_train_lda = pd.DataFrame(x_train_lda, columns=['LD1'], index=x_train.index)
x_test_lda = pd.DataFrame(x_test_lda, columns=['LD1'], index=x_test.index)

x_train_lda = sm.add_constant(x_train_lda, prepend=False)
x_test_lda = sm.add_constant(x_test_lda, prepend=False)

mod3 = sm.Logit(y_train, x_train_lda).fit()
x_test_lda = sm.add_constant(x_test_lda, prepend=False)
y_pred = mod3.predict(x_test_lda)
y_pred = (y_pred>=0.5).astype(int)
print(confusion_matrix(y_test,y_pred))

Optimization terminated successfully.
         Current function value: 0.378361
         Iterations 7
[[168  42]
 [ 50 140]]