<a href="https://colab.research.google.com/github/siddhidamkondwar/Practical_Machine_Learning/blob/main/ML_5_6_26_DAY4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from numpy import linalg
import scipy
from scipy import stats
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import norm, t
from scipy.stats import expon
from collections import Counter
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
import statsmodels.stats
from statsmodels.stats.proportion import proportions_ztest
from scipy.stats import chisquare
from scipy.stats import chi2_contingency
from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson
from statsmodels.stats.rates import test_poisson_2indep
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
df =  pd.read_excel('/content/StudentData.xlsx')

In [ ]:
df = df.drop('Unnamed: 0', axis=1)

# Split for train-test
x_train, x_test, y_train, y_test = train_test_split(df.drop('Marks', axis=1),df.Marks, test_size=0.2, random_state=20)

# Add constant term
x_train = sm.add_constant(x_train, prepend=False)
x_test = sm.add_constant(x_test, prepend=False)

# Prepare the model
mod1 = sm.OLS(y_train,x_train).fit()

print(mod1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Marks   R-squared:                       0.722
Model:                            OLS   Adj. R-squared:                  0.682
Method:                 Least Squares   F-statistic:                     17.96
Date:                Sat, 06 Jun 2026   Prob (F-statistic):           1.38e-15
Time:                        04:06:44   Log-Likelihood:                -266.22
No. Observations:                  80   AIC:                             554.4
Df Residuals:                      69   BIC:                             580.6
Df Model:                          10
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
StudyHours        4.9723      2.752      1.807      0.075      -0.518      10.462
PracticeTests     6.1438      3.575      1.719      0.090      -0.987      13.275
RevisionHours    -0.7379      2.690     -0.274      0.785      -6.105       4.629
CoachingHours    -2.0754      3.521     -0.589      0.558      -9.100       4.949
Attendance        1.1862      0.170      6.996      0.000       0.848       1.524
MobileUsage       0.5540      0.473      1.170      0.246      -0.390       1.498
NetflixHours      0.1115      0.402      0.277      0.783      -0.691       0.914
GamingHours       0.1750      0.567      0.309      0.759      -0.956       1.306
SocialMedia       0.1079      0.494      0.219      0.828      -0.877       1.093
SportsHours      -1.2888      0.902     -1.428      0.158      -3.089       0.511
const            37.8871     15.547      2.437      0.017       6.873      68.902
==============================================================================
Omnibus:                        5.697   Durbin-Watson:                   2.195
Prob(Omnibus):                  0.058   Jarque-Bera (JB):                5.022
Skew:                          -0.493   Prob(JB):                       0.0812
Kurtosis:                       3.730   Cond. No.                     1.65e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
df.corr()

,StudyHours,PracticeTests,RevisionHours,CoachingHours,Attendance,MobileUsage,NetflixHours,GamingHours,SocialMedia,SportsHours,Marks
StudyHours,1.000000,-0.137275,0.985756,-0.166741,-0.139500,-0.148479,0.039702,-0.119595,-0.116330,0.054158,0.461595
PracticeTests,-0.137275,1.000000,-0.136466,0.982391,0.187605,-0.129208,0.083350,0.098441,0.137525,0.060396,0.455356
RevisionHours,0.985756,-0.136466,1.000000,-0.164784,-0.149062,-0.170147,0.023863,-0.119828,-0.152964,0.079607,0.448704
CoachingHours,-0.166741,0.982391,-0.164784,1.000000,0.230122,-0.115819,0.088085,0.076729,0.100994,0.056112,0.444800
Attendance,-0.139500,0.187605,-0.149062,0.230122,1.000000,-0.090584,0.113714,-0.018171,0.115444,-0.152492,0.430057
MobileUsage,-0.148479,-0.129208,-0.170147,-0.115819,-0.090584,1.000000,-0.086980,0.093279,-0.107880,-0.072796,-0.104220
NetflixHours,0.039702,0.083350,0.023863,0.088085,0.113714,-0.086980,1.000000,-0.106991,0.125457,0.082534,0.140267
GamingHours,-0.119595,0.098441,-0.119828,0.076729,-0.018171,0.093279,-0.106991,1.000000,-0.065969,0.217792,-0.040819
SocialMedia,-0.116330,0.137525,-0.152964,0.100994,0.115444,-0.107880,0.125457,-0.065969,1.000000,-0.212731,0.066168
SportsHours,0.054158,0.060396,0.079607,0.056112,-0.152492,-0.072796,0.082534,0.217792,-0.212731,1.000000,-0.086149
Marks,0.461595,0.455356,0.448704,0.444800,0.430057,-0.104220,0.140267,-0.040819,0.066168,-0.086149,1.000000

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

x = df.drop('Marks', axis=1)

vif_df = pd.DataFrame()
vif_df['Variable'] = x.columns
vif_df['VIF'] = [
    variance_inflation_factor(x.values, i)
    for i in range(x.shape[1])
]

print("\nVIF VALUES")
print(vif_df.sort_values('VIF', ascending=False))

VIF VALUES
        Variable         VIF
3  CoachingHours  448.533988
1  PracticeTests  444.040942
0     StudyHours  436.685659
2  RevisionHours  407.771297
4     Attendance   60.859442
8    SocialMedia   15.561370
5    MobileUsage    7.811828
9    SportsHours    5.976866
7    GamingHours    5.890728
6   NetflixHours    4.989462

In [ ]:
# we notice that the same factors which has very high co relation coefficiet amongs them are also having high VIF value

In [ ]:
x = df.drop(['Marks','CoachingHours','StudyHours'], axis=1)

In [ ]:
vif_df = pd.DataFrame()
vif_df['Variable'] = x.columns
vif_df['VIF'] = [
    variance_inflation_factor(x.values, i)
    for i in range(x.shape[1])
]

print("\nVIF VALUES")
print(vif_df.sort_values('VIF', ascending=False))

VIF VALUES
        Variable        VIF
2     Attendance  54.670801
0  PracticeTests  14.844545
6    SocialMedia  13.981452
1  RevisionHours  10.080112
3    MobileUsage   7.657400
7    SportsHours   5.898704
5    GamingHours   5.745141
4   NetflixHours   4.937682

In [ ]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import StandardScaler

x = df.drop('Marks', axis=1)
y=df.Marks
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
x_scaled = pd.DataFrame(x_scaled, columns=x.columns)

from sklearn.linear_model import LinearRegression
regr1 = LinearRegression()
regr1.fit(x_scaled,y)
regr1.coef_
'''
regr1.coef_
Out[37]:
array([ 5.50805023,  7.25112668,  2.0336992 , -1.39211411,  5.28411473,
        1.09301416,  0.58200739,  0.0777879 ,  0.1418704 , -1.05017386])
'''
regr1.intercept_
regr1.feature_names_in_
'''
array(['StudyHours', 'PracticeTests', 'RevisionHours', 'CoachingHours',
       'Attendance', 'MobileUsage', 'NetflixHours', 'GamingHours',
       'SocialMedia', 'SportsHours'], dtype=object)
'''

ridge = Ridge(alpha=10)
ridge.fit(x_scaled,y)
ridge.coef_
'''
array([ 3.82980281,  3.32971683,  3.3198266 ,  2.26051693,  4.63360394,
        0.85365738,  0.59599171,  0.14077832,  0.33850811, -1.0176817 ])
'''
ridge.intercept_
regr1.feature_names_in_

lasso = Lasso(alpha=1)          #if we increase the value of alpha that means we are applying very high penlty
lasso.fit(x_scaled,y)
lasso.coef_
'''
array([ 6.04772327,  4.72885822,  0.        ,  0.        ,  4.34663537,
        0.        ,  0.        , -0.        ,  0.        , -0.03101151])
'''
lasso.intercept_

np.float64(185.09500000000003)

# prctice

In [ ]:
lasso = Lasso(alpha=10)          #if we increase the value of alpha that means we are applying very high penlty
lasso.fit(x_scaled,y)
lasso.coef_

array([ 0.,  0.,  0.,  0.,  0., -0.,  0., -0.,  0., -0.])

In [ ]:
lasso = Lasso(alpha=6)          #if we increase the value of alpha that means we are applying very high penlty
lasso.fit(x_scaled,y)
lasso.coef_

array([ 0.,  0.,  0.,  0.,  0., -0.,  0., -0.,  0., -0.])

In [ ]:
ridge = Ridge(alpha=1)
ridge.fit(x_scaled,y)
ridge.coef_

array([ 4.78692825,  5.49382498,  2.762101  ,  0.34315597,  5.15545601,
        1.06778763,  0.58644981,  0.12693041,  0.24606698, -1.06009871])

In [ ]:
# To get the optimum value of alpha for Lasso regression

from sklearn.linear_model import LassoCV
lassocv=LassoCV(cv=5)
lassocv.fit(x_scaled,y)
lassocv.alpha_

np.float64(0.46968573975480105)

In [ ]:
from sklearn.linear_model import RidgeCV
ridgecv=RidgeCV(cv=5)
ridgecv.fit(x_scaled,y)
ridgecv.alpha_

np.float64(10.0)

# Logistic Regression

Binary = 2 possible resopnses



Nominal = 2 possible levels

Ordinal = level have logical order


Event occurs = p

Event not occurs = 1-p

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name = 'diabetes')

df =df[['Glucose','BloodPressure','Age','DietType','Outcome']]

x = df.drop('Outcome', axis=1)
y = df.Outcome

diet_dummy = pd.get_dummies(x.DietType, drop_first=True, prefix='Diet').astype(int)
x = x.drop('DietType', axis=1)
x = pd.concat([x, diet_dummy], axis=1)

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=20)

x_train = sm.add_constant(x_train, prepend=False)
x_test = sm.add_constant(x_test, prepend=False)
mod3 = sm.Logit(y_train, x_train).fit()
print(mod3.summary())

Optimization terminated successfully.
         Current function value: 0.333614
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                Outcome   No. Observations:                  614
Model:                          Logit   Df Residuals:                      608
Method:                           MLE   Df Model:                            5
Date:                Sat, 06 Jun 2026   Pseudo R-squ.:                  0.4848
Time:                        04:06:45   Log-Likelihood:                -204.84
converged:                       True   LL-Null:                       -397.59
Covariance Type:            nonrobust   LLR p-value:                 3.933e-81
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Glucose           0.0368      0.005      7.867      0.000       0.028       0.046
BloodPressure     0.0058      0.007      0.850      0.395      -0.008       0.019
Age               0.0317      0.011      2.908      0.004       0.010       0.053
Diet_2           -3.9276      0.323    -12.142      0.000      -4.562      -3.294
Diet_3           -2.7806      0.344     -8.076      0.000      -3.455      -2.106
const            -4.3877      0.730     -6.012      0.000      -5.818      -2.957
=================================================================================

In [ ]:
y_pred = mod3.predict(x_test)

In [ ]:
y_pred

143    0.067186
14     0.455764
504    0.044509
557    0.300460
736    0.074480
         ...
57     0.119158
140    0.195656
713    0.084194
673    0.074613
559    0.075453
Length: 154, dtype: float64

In [ ]:
y_test

143    1
14     1
504    0
557    0
736    0
      ..
57     0
140    0
713    0
673    0
559    0
Name: Outcome, Length: 154, dtype: int64

In [ ]:
#response does not depend on predictor

#moving from diet 1 to diet 2 probability of diet 2 will decrease

In [ ]:
 0.0317 / 0.011

2.881818181818182

In [ ]:
x_train.iloc[1]

Glucose          191.0
BloodPressure     68.0
Age               34.0
Diet_2             1.0
Diet_3             0.0
const              1.0
Name: 260, dtype: float64

In [ ]:
z=0.0368*191 + 0.0058*68 + 0.0317*34 +( - 3.9276*1) +(- 2.7806*0 )+(- 4.3877*1)

In [ ]:
z

0.18569999999999975

In [ ]:
1/(1+2.718**(-z))

0.5462872743077929

In [ ]:
x_test.iloc[1]

Glucose          166.0
BloodPressure     72.0
Age               51.0
Diet_2             1.0
Diet_3             0.0
const              1.0
Name: 14, dtype: float64

In [ ]:
z=0.0368*166 + 0.0058*72 + 0.0317*51  +( - 3.9276*1) +(- 2.7806*0 )+(- 4.3877*1)

In [ ]:
z

-0.17219999999999924

In [ ]:
1/(1+2.718**(-z))

0.45706049574602176

In [ ]:
mydata = pd.DataFrame([[100,75,50,1,0,1],[100,75,51,1,0,1]], columns = x_train.columns)

In [ ]:
mydata

   Glucose  BloodPressure  Age  Diet_2  Diet_3  const
0      100             75   50       1       0      1
1      100             75   51       1       0      1

In [ ]:
mypreds = mod3.predict(mydata)

In [ ]:
mypreds

0    0.067899
1    0.069934
dtype: float64

In [ ]:
LOR_51 = np.log(0.069934 /(1-0.069934))

In [ ]:
LOR_50 = np.log(0.067899/(1-0.067899))

In [ ]:
LOR_51 - LOR_50

np.float64(0.03171625976306691)

In [ ]:
# coeficient of age 0.0317 indicates that when the age increses by one unit the change/increse  in the log of odds ratio in favor of getting diabetis

In [ ]:
#output of sigmoid always between 0 and 1
#domain= 0,1p

In [ ]:
mydata = pd.DataFrame([[100,75,50,1,0,1],[100,75,50,0,0,1]], columns = x_train.columns)

In [ ]:
mypreds = mod3.predict(mydata)

In [ ]:
mypreds

0    0.067899
1    0.787203
dtype: float64

In [ ]:
np.log(0.067899/(1-0.067899)) - np.log(0.787203/(1-0.787203))

np.float64(-3.927567368079736)