<a href="https://colab.research.google.com/github/siddhidamkondwar/Practical_Machine_Learning/blob/main/ML_6_6_26_DAY5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ONE HOT ENCODING :

USED FOR NOMINAL SCALE VARIABLES (NO LOGICAL ORDER)

NOT USEFULWHEN NUMBER OF CATEGORIES ARE TOO LARGE

REGRESSION ,ANN,KNN,SVM

# ORDINAL ENCODING

VARIABLES WITH INHERENT RANKING OR RATING

PRESERVE LOGICAL ORDER

# FREQUENCY ENCODING (COUNTS)

# BINARY ENCODING

USED WHEN NO OF CATAGOERS ARE TOO LARGE

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({
    'Education':[
        'Graduate',
        'PG',
        'High School',
        'Graduate',
        'PG'
    ]
})

education_map = {
    'High School':1,
    'Graduate':2,
    'PG':3
}

df['Education_Encoded'] = (
    df['Education']
    .map(education_map)
)

print(df)

     Education  Education_Encoded
0     Graduate                  2
1           PG                  3
2  High School                  1
3     Graduate                  2
4           PG                  3

In [ ]:
# Frequency encoding
df = pd.DataFrame({
    'City':[
        'Mumbai',
        'Mumbai',
        'Mumbai',
        'Delhi',
        'Delhi',
        'Pune'
    ]
})

freq = df.City.value_counts()

df['City_Frequency'] = (df.City.map(freq))

In [ ]:
df

     City  City_Frequency
0  Mumbai               3
1  Mumbai               3
2  Mumbai               3
3   Delhi               2
4   Delhi               2
5    Pune               1

# BINARY ENCODERS

In [ ]:
pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.9/85.9 kB 2.5 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0

In [ ]:
df = pd.DataFrame({
    'City': [
        'Mumbai',
        'Pune',
        'Delhi',
        'Chennai',
        'Kolkata'
    ]
})


#pip install category_encoders

from category_encoders import BinaryEncoder
encoder = BinaryEncoder(cols=['City'])
df_encoded = encoder.fit_transform(df)
print(df_encoded)

   City_0  City_1  City_2
0       0       0       1
1       0       1       0
2       0       1       1
3       1       0       0
4       1       0       1

In [ ]:
df_encoded = encoder.transform(df)
result = pd.concat([df, df_encoded], axis=1)
print(result)

      City  City_0  City_1  City_2
0   Mumbai       0       0       1
1     Pune       0       1       0
2    Delhi       0       1       1
3  Chennai       1       0       0
4  Kolkata       1       0       1

In [ ]:
df

      City
0   Mumbai
1     Pune
2    Delhi
3  Chennai
4  Kolkata